// <auto-generated />
namespace SkateSpotsFinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedSkateLoggerModelandControllerwithpropertiesassignedtoit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedSkateLoggerModelandControllerwithpropertiesassignedtoit));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221431035_Added SkateLogger Model and Controller with properties assigned to it."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
