// <auto-generated />
namespace SkateSpotsFinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangedListoftrickstostringtricknameanddeletedreaddedcontroller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedListoftrickstostringtricknameanddeletedreaddedcontroller));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221535065_Changed List of tricks to string trick name and deleted, re added controller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
