// <auto-generated />
namespace SkateSpotsFinalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LearnTricksModelandControlleradded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LearnTricksModelandControlleradded));
        
        string IMigrationMetadata.Id
        {
            get { return "201705221513211_Learn Tricks Model and Controller added. "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
